### ISSUE TITLE
Add basic speech2text functionality based on google ASR api

### ISSUE THREAD

**Issue by tyiannak** [christitol/speech-to-sql#4]
1) create google api account and respective key
2)  use https://github.com/tyiannak/readys/blob/master/asr.py as a baseline. 
3) create requirements file

also, side tasks: check ffmpeg, git etc

**Comment by christitol** [comment]
1. Created google api account and retrieved key 
2. Used https://github.com/tyiannak/readys/blob/master/asr.py 
3. Created requirements file
